name: Scheduled Hello World

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  # Optional: Allow manual trigger
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or a specific version

      - name: Install dependencies
        run: bun install

      - name: Run script
        run: bun run index.ts

      - name: Commit log file (optional)
        if: always() # Run even if previous steps fail
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update log file
          file_pattern: output.log

permissions:
  contents: write